//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaABR.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PruebaABREntities : DbContext
    {
        public PruebaABREntities()
            : base("name=PruebaABREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Asignatura> Asignatura { get; set; }
        public virtual DbSet<EstudianteAsignatura> EstudianteAsignatura { get; set; }
        public virtual DbSet<ProfesorAsignatura> ProfesorAsignatura { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Configuracion> Configuracion { get; set; }
    }
}
