//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaABR.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int ConfiguracionID { get; set; }
        public string Key { get; set; }
        public string Valor { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
