//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaABR.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int PersonaID { get; set; }
        public string Identificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> RolID { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
