//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaABR.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesorAsignatura
    {
        public int ProfesorAsignaturaID { get; set; }
        public Nullable<int> PersonaID { get; set; }
        public Nullable<int> AsignaturaID { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
